# Generated by Django 2.1.3 on 2019-03-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190321_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bido',
            new_name='bio',
        ),
    ]
