# Generated by Django 2.1.3 on 2019-04-11 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='to_date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='from_hour',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='to_hour',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
