# Generated by Django 2.1.3 on 2019-03-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
