# Generated by Django 2.1.3 on 2019-03-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_guest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Declined'), ('A', 'Accepted'), ('C', 'Canceled'), ('AC', 'accomplished')], default='Pending', max_length=30),
        ),
    ]
