# Generated by Django 2.1.3 on 2019-03-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest_email',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('D', 'Declined'), ('A', 'Accepted'), ('C', 'Canceled'), ('AC', 'Accomplished')], default='Pending', max_length=30),
        ),
    ]
