# Generated by Django 2.1.3 on 2019-04-25 22:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0008_auto_20190408_1821'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('guest', 'created_by', 'date')},
        ),
    ]
