# Generated by Django 2.1.3 on 2019-04-30 22:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0009_auto_20190425_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_contact',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Ingresa un correo electrónico')]),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('date', 'created_by', 'guest')},
        ),
    ]
